-- Table: public.user_record

DROP TABLE user_record;

CREATE TABLE user_record
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    create_time timestamp without time zone,
    email character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    update_time timestamp without time zone,
    CONSTRAINT user_record_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE public.user_record
    OWNER to postgres;
